# This file is auto-generated from the current state of the database. Instead of editing this file, 
# please use the migrations feature of Active Record to incrementally modify your database, and
# then regenerate this schema definition.
#
# Note that this schema.rb definition is the authoritative source for your database schema. If you need
# to create the application database on another system, you should be using db:schema:load, not running
# all the migrations from scratch. The latter is a flawed and unsustainable approach (the more migrations
# you'll amass, the slower it'll run and the greater likelihood for issues).
#
# It's strongly recommended to check this file into your version control system.

ActiveRecord::Schema.define(:version => 20130109195142) do

  create_table "seeds", :force => true do |t|
    t.integer  "batch_id"
    t.text     "content"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.boolean  "dirty"
    t.datetime "time_setup"
  end

  create_table "sessions", :force => true do |t|
    t.string   "session_id", :null => false
    t.text     "data"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  add_index "sessions", ["session_id"], :name => "index_sessions_on_session_id"
  add_index "sessions", ["updated_at"], :name => "index_sessions_on_updated_at"

  create_table "topics", :force => true do |t|
    t.integer  "position"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.string   "name"
    t.text     "link"
  end

  create_table "users", :force => true do |t|
    t.integer  "bildung",                      :limit => 255
    t.integer  "alter"
    t.integer  "retweet_2_clicked"
    t.integer  "new_tweet_clicked"
    t.integer  "geschlecht",                   :limit => 255
    t.datetime "created_at"
    t.datetime "updated_at"
    t.integer  "martial_status"
    t.integer  "language"
    t.integer  "country"
    t.integer  "years"
    t.integer  "twitter_account"
    t.integer  "income"
    t.integer  "area"
    t.integer  "children"
    t.integer  "employment"
    t.string   "employment_text"
    t.integer  "position"
    t.string   "position_text"
    t.string   "bildung_text"
    t.integer  "organization"
    t.string   "organization_text"
    t.integer  "private_pc"
    t.integer  "private_mobile"
    t.integer  "work_pc"
    t.integer  "work_mobile"
    t.integer  "public"
    t.integer  "favorite_2_clicked"
    t.string   "leader_text"
    t.integer  "reply_2_clicked"
    t.string   "reply_text"
    t.string   "tweet_text"
    t.string   "search"
    t.float    "retweet_time_m1"
    t.float    "favorite_time_m1"
    t.float    "message_hover_m1"
    t.float    "reply_time_m1"
    t.float    "new_tweet_time"
    t.integer  "compose_tweet_clicked"
    t.string   "tweet_text_n"
    t.string   "seen_message_1"
    t.string   "ol_1"
    t.string   "ol_2"
    t.string   "ol_3"
    t.string   "ol_4"
    t.string   "ol_5"
    t.string   "ol_6"
    t.string   "ol_7"
    t.string   "ol_8"
    t.string   "ol_9"
    t.string   "ol_10"
    t.string   "ol_11"
    t.string   "ol_12"
    t.boolean  "seen_person",                  :limit => 255
    t.float    "open_time_m1"
    t.float    "search_time"
    t.boolean  "seen_retweet_message1",        :limit => 255
    t.integer  "expand_2_clicked"
    t.float    "experiment_time"
    t.boolean  "seen_at",                      :limit => 255
    t.integer  "search_clicked"
    t.boolean  "seen_multiple_messages",       :limit => 255
    t.string   "seen_message_2"
    t.integer  "reply_1_clicked"
    t.integer  "favorite_1_clicked"
    t.integer  "retweet_1_clicked"
    t.integer  "expand_1_clicked"
    t.integer  "results"
    t.integer  "situation"
    t.string   "account_name"
    t.integer  "number_followers"
    t.integer  "number_followeees"
    t.integer  "number_messages"
    t.integer  "avg_tweet_number"
    t.integer  "avg_at_replies"
    t.integer  "avg_read_tweets"
    t.integer  "avg_stories"
    t.integer  "avg_trend"
    t.integer  "avg_retweet"
    t.integer  "avg_follow"
    t.integer  "avg_login"
    t.integer  "avg_search_keywords"
    t.integer  "avg_search_accounts"
    t.integer  "avg_activities_friends"
    t.integer  "avg_who_to_follow"
    t.integer  "avg_browse_categories"
    t.integer  "avg_find_friends"
    t.integer  "avg_create_lists"
    t.integer  "avg_add_accounts_lists"
    t.integer  "avg_subscribe_lists"
    t.integer  "avg_delete_accounts_lists"
    t.integer  "avg_unfollow_account"
    t.integer  "avg_favorite_tweets"
    t.integer  "surf_twitter_week"
    t.integer  "surf_twitter_weekend"
    t.integer  "avg_private_replies"
    t.string   "seen_seed"
    t.integer  "batch_id"
    t.float    "retweet_time_m2"
    t.float    "favorite_time_m2"
    t.float    "message_hover_m2"
    t.float    "reply_time_m2"
    t.float    "open_time_m2"
    t.string   "reply_text2"
    t.integer  "message_important"
    t.integer  "message_meaningful"
    t.integer  "message_for_me"
    t.integer  "message_remember"
    t.integer  "message_value"
    t.integer  "message_relevant"
    t.integer  "message_useful"
    t.integer  "message_attention"
    t.integer  "message_interest"
    t.integer  "message_ideas"
    t.integer  "message_helpful"
    t.integer  "message_informative"
    t.integer  "intention1_write"
    t.integer  "intention2_write"
    t.integer  "intention3_write"
    t.integer  "intention1_discover_stories"
    t.integer  "intention2_discover_stories"
    t.integer  "intention3_discover_stories"
    t.integer  "intention1_discover_trends"
    t.integer  "intention2_discover_trends"
    t.integer  "intention3_discover_trends"
    t.integer  "intention1_follow"
    t.integer  "intention2_follow"
    t.integer  "intention3_follow"
    t.integer  "intention1_unfollow"
    t.integer  "intention2_unfollow"
    t.integer  "intention3_unfollow"
    t.integer  "intention1_create_lists"
    t.integer  "intention2_create_lists"
    t.integer  "intention3_create_lists"
    t.integer  "intention1_add_to_lists"
    t.integer  "intention2_add_to_lists"
    t.integer  "intention3_add_to_lists"
    t.integer  "intention1_unsubscribe_lists"
    t.integer  "intention2_unsubscribe_lists"
    t.integer  "intention3_unsubscribe_lists"
    t.integer  "intention1_subscribe_lists"
    t.integer  "intention2_subscribe_lists"
    t.integer  "intention3_subscribe_lists"
    t.string   "reason_nrt"
    t.string   "reason_nfav"
    t.string   "reason_nrep"
    t.string   "reason_nexp"
    t.text     "mousetracks"
    t.integer  "pass_time"
    t.integer  "entertain_myself"
    t.integer  "occupy_time"
    t.integer  "time_bored"
    t.integer  "forget_worries"
    t.integer  "help_others"
    t.integer  "support_others"
    t.integer  "show_encouragement"
    t.integer  "contribute"
    t.integer  "new_friends"
    t.integer  "new_people"
    t.integer  "get_know_other"
    t.integer  "keep_in_touch"
    t.integer  "find_people"
    t.integer  "communicate"
    t.integer  "gather_information"
    t.integer  "find_out_things"
    t.integer  "look_for_information"
    t.integer  "knowledgeable_individual"
    t.integer  "answers_questions"
    t.integer  "keep_connect"
    t.integer  "find_out"
    t.integer  "deepen_relationships"
    t.integer  "far_away"
    t.string   "interest_list"
    t.integer  "came_across_same_intrest"
    t.integer  "avg_unsubscribe_lists"
    t.string   "other_str_sup_topic"
    t.integer  "other_sup_topic",              :limit => 255
    t.integer  "defence",                      :limit => 255
    t.integer  "diplomacy",                    :limit => 255
    t.integer  "elections",                    :limit => 255
    t.integer  "espionage",                    :limit => 255
    t.integer  "foreign_aid",                  :limit => 255
    t.integer  "government",                   :limit => 255
    t.integer  "human_rights",                 :limit => 255
    t.integer  "parliament",                   :limit => 255
    t.integer  "parties",                      :limit => 255
    t.integer  "refugees",                     :limit => 255
    t.integer  "regional_authorities",         :limit => 255
    t.integer  "state_budget",                 :limit => 255
    t.integer  "treaties",                     :limit => 255
    t.integer  "constitution",                 :limit => 255
    t.integer  "interior_policies",            :limit => 255
    t.integer  "migration",                    :limit => 255
    t.integer  "referenda",                    :limit => 255
    t.integer  "citizens_initiative",          :limit => 255
    t.integer  "lobbying",                     :limit => 255
    t.integer  "nuclear_policies",             :limit => 255
    t.integer  "local_authorities"
    t.integer  "slider"
    t.integer  "dk_pol_percentage"
    t.integer  "people_interested_phone"
    t.integer  "trad_mass_med_online"
    t.integer  "person_contact_online"
    t.integer  "twitter_privat_work"
    t.integer  "locals_phone"
    t.integer  "came_across_twitter_list"
    t.integer  "self_aggregated"
    t.integer  "tv"
    t.integer  "radio"
    t.integer  "magazin"
    t.integer  "newspaper"
    t.integer  "tv_website"
    t.integer  "tv_sn"
    t.integer  "tv_mb"
    t.integer  "tv_rss"
    t.integer  "tv_newsletter"
    t.integer  "radio_website"
    t.integer  "radio_sn"
    t.integer  "radio_mb"
    t.integer  "radio_rss"
    t.integer  "radio_newsletter"
    t.integer  "magazin_website"
    t.integer  "magazin_sn"
    t.integer  "magazin_mb"
    t.integer  "magazin_rss"
    t.integer  "magazin_newsletter"
    t.integer  "newspaper_website"
    t.integer  "newspaper_sn"
    t.integer  "newspaper_mb"
    t.integer  "newspaper_rss"
    t.integer  "newspaper_newsletter"
    t.integer  "people_interested"
    t.integer  "locals"
    t.integer  "aquaintances"
    t.integer  "contact_friends"
    t.integer  "colleagues"
    t.integer  "experts"
    t.integer  "contact_ol"
    t.integer  "people_interested_email"
    t.integer  "people_interested_sn"
    t.integer  "people_interested_mb"
    t.integer  "people_interested_forum"
    t.integer  "people_interested_chat"
    t.integer  "locals_email"
    t.integer  "locals_sn"
    t.integer  "locals_mb"
    t.integer  "locals_forum"
    t.integer  "locals_chat"
    t.integer  "aquaintances_email"
    t.integer  "aquaintances_sn"
    t.integer  "aquaintances_mb"
    t.integer  "aquaintances_forum"
    t.integer  "aquaintances_chat"
    t.integer  "contact_friends_email"
    t.integer  "contact_friends_sn"
    t.integer  "contact_friends_mb"
    t.integer  "contact_friends_forum"
    t.integer  "contact_friends_chat"
    t.integer  "colleagues_email"
    t.integer  "colleagues_sn"
    t.integer  "colleagues_mb"
    t.integer  "colleagues_forum"
    t.integer  "colleagues_chat"
    t.integer  "experts_email"
    t.integer  "experts_sn"
    t.integer  "experts_mb"
    t.integer  "experts_forum"
    t.integer  "experts_chat"
    t.integer  "contact_ol_email"
    t.integer  "contact_ol_sn"
    t.integer  "contact_ol_mb"
    t.integer  "contact_ol_forum"
    t.integer  "contact_ol_chat"
    t.integer  "blogs"
    t.integer  "search_engine"
    t.integer  "goverment_site"
    t.integer  "community_site"
    t.integer  "other_sources"
    t.string   "other_sources_txt"
    t.integer  "heard_mass_media"
    t.integer  "heard_internet"
    t.integer  "read_retweet"
    t.integer  "read_reply"
    t.integer  "heard_friends_follow"
    t.integer  "heard_friends_interact"
    t.integer  "heard_friends_recommend"
    t.integer  "heard_friends_write"
    t.integer  "heard_friends_follow_nf"
    t.integer  "heard_friends_interact_nf"
    t.integer  "heard_friends_recommend_nf"
    t.integer  "heard_friends_write_nf"
    t.integer  "came_accross_wtf"
    t.integer  "came_across_bc"
    t.integer  "came_across_stories"
    t.integer  "knew_friends"
    t.integer  "knew_colleagues"
    t.integer  "knew_aquaintances"
    t.integer  "met_informal"
    t.integer  "met_formal"
    t.integer  "other_reasons"
    t.string   "other_reasons_txt"
    t.integer  "aquaintances_phone"
    t.integer  "contact_friends_phone"
    t.integer  "colleagues_phone"
    t.integer  "experts_phone"
    t.integer  "contact_ol_phone"
    t.text     "seen_message_long"
    t.text     "seen_headline"
    t.integer  "link_clicked"
    t.float    "follow_m1"
    t.integer  "beh_exp_reply"
    t.integer  "follow_1_clicked"
    t.integer  "beh_exp_retweet"
    t.integer  "reply_pr_relevant"
    t.integer  "reply_pr_meaningful"
    t.integer  "reply_pr_important"
    t.integer  "reply_pr_significant"
    t.integer  "reply_oc_relevant"
    t.integer  "reply_oc_meaningful"
    t.integer  "reply_oc_important"
    t.integer  "reply_oc_significant"
    t.integer  "favorite_pr_relevant"
    t.integer  "favorite_pr_meaningful"
    t.integer  "favorite_pr_important"
    t.integer  "favorite_pr_significant"
    t.integer  "dip_neg"
    t.integer  "dip_oth"
    t.integer  "ele_neg"
    t.integer  "ele_oth"
    t.integer  "retweet_pr_relevant"
    t.integer  "retweet_pr_meaningful"
    t.integer  "retweet_pr_important"
    t.integer  "retweet_pr_significant"
    t.integer  "retweet_oc_relevant"
    t.integer  "retweet_oc_meaningful"
    t.integer  "retweet_oc_important"
    t.integer  "retweet_oc_significant"
    t.string   "open_reasons"
    t.integer  "reply_pr_relevant_ck"
    t.integer  "reply_pr_meaningful_ck"
    t.integer  "reply_pr_important_ck"
    t.integer  "reply_pr_significant_ck"
    t.integer  "reply_oc_relevant_ck"
    t.integer  "reply_oc_meaningful_ck"
    t.integer  "reply_oc_important_ck"
    t.integer  "reply_oc_significant_ck"
    t.integer  "favorite_pr_relevant_ck"
    t.integer  "favorite_pr_meaningful_ck"
    t.integer  "favorite_pr_important_ck"
    t.integer  "favorite_pr_significant_ck"
    t.integer  "esp_neg"
    t.integer  "def_oth"
    t.integer  "avg_read_twtimes"
    t.integer  "def_neg"
    t.integer  "retweet_pr_relevant_ck"
    t.integer  "retweet_pr_meaningful_ck"
    t.integer  "retweet_pr_important_ck"
    t.integer  "retweet_pr_significant_ck"
    t.integer  "retweet_oc_relevant_ck"
    t.integer  "retweet_oc_meaningful_ck"
    t.integer  "retweet_oc_important_ck"
    t.integer  "retweet_oc_significant_ck"
    t.string   "open_reasons_others"
    t.string   "email"
    t.integer  "esp_oth"
    t.integer  "for_neg"
    t.integer  "for_oth"
    t.integer  "gov_neg"
    t.integer  "gov_oth"
    t.integer  "hum_neg"
    t.integer  "hum_oth"
    t.integer  "loc_neg"
    t.integer  "loc_oth"
    t.integer  "parl_neg"
    t.integer  "parl_oth"
    t.integer  "part_neg"
    t.integer  "part_oth"
    t.integer  "refu_neg"
    t.integer  "refu_oth"
    t.integer  "auth_neg"
    t.integer  "auth_oth"
    t.integer  "bud_neg"
    t.integer  "bud_oth"
    t.integer  "tre_neg"
    t.integer  "tre_oth"
    t.integer  "cons_neg"
    t.integer  "cons_oth"
    t.integer  "int_neg"
    t.integer  "int_oth"
    t.integer  "mig_neg"
    t.integer  "mig_oth"
    t.integer  "cit_neg"
    t.integer  "cit_oth"
    t.integer  "refe_neg"
    t.integer  "refe_oth"
    t.integer  "nuc_neg"
    t.integer  "nuc_oth"
    t.integer  "lob_neg"
    t.integer  "lob_oth"
    t.integer  "oth_neg"
    t.integer  "oth_oth"
    t.string   "oth_neg_txt"
    t.string   "oth_oth_txt"
    t.integer  "beh_exp_favorite"
    t.integer  "beh_exp_write"
    t.integer  "t_imp_int_retweet"
    t.integer  "t_imp_int_reply"
    t.integer  "t_imp_int_favorite"
    t.integer  "t_imp_int_write"
    t.integer  "o_imp_int_retweet"
    t.integer  "o_imp_int_reply"
    t.integer  "o_imp_int_favorite"
    t.integer  "o_imp_int_write"
    t.integer  "cbx_write"
    t.integer  "cbx_discover_stories"
    t.integer  "cbx_discover_trends"
    t.integer  "cbx_follow"
    t.integer  "cbx_unfollow"
    t.integer  "cbx_create_lists"
    t.integer  "cbx_add_to_lists"
    t.integer  "cbx_unsubscribe_lists"
    t.integer  "cbx_subscribe_lists"
    t.integer  "any_mistakes"
    t.string   "mistake_txt"
    t.integer  "act_af_tw"
    t.integer  "uinf_an_sco"
    t.integer  "irp_imagine"
    t.integer  "irp_act"
    t.integer  "irp_keep"
    t.integer  "cr_imagine"
    t.integer  "cr_act"
    t.integer  "cr_keep"
  end

end
